apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: polis-data
  labels:
    app.kubernetes.io/name: polis
    app.kubernetes.io/component: mailbox
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
