---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: polis-controller
rules:
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - polis.dev
  resources:
  - agents
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - polis.dev
  resources:
  - agents/finalizers
  verbs:
  - update
- apiGroups:
  - polis.dev
  resources:
  - agents/status
  verbs:
  - get
  - patch
  - update
